package com.example.carcollection.presentation.add_edit_car

import com.example.carcollection.R

val backgroundResourceMap = mapOf(
    "fondo" to R.drawable.fondo,
    "fondo2" to R.drawable.fondo2,
    "fondo3" to R.drawable.fondo3,
    "fondo4" to R.drawable.fondo4,
    "fondo5" to R.drawable.fondo5,
    "fondo6" to R.drawable.fondo6,
    "fondo7" to R.drawable.fondo7,
    "fondo8" to R.drawable.fondo8,
    "fondo9" to R.drawable.fondo9,
    "fondo10" to R.drawable.fondo10,
    "fondo11" to R.drawable.fondo11,
    "fondo12" to R.drawable.fondo12,
    "fondo13" to R.drawable.fondo13,
    "fondo14" to R.drawable.fondo14,
    "fondo15" to R.drawable.fondo15,
    "fondo16" to R.drawable.fondo16,
    "fondo17" to R.drawable.fondo17,
    "fondo18" to R.drawable.fondo18,
    "fondo19" to R.drawable.fondo19,
    "fondo20" to R.drawable.fondo20,
    "fondo21" to R.drawable.fondo21,
    "fondo22" to R.drawable.fondo22,
    "fondo23" to R.drawable.fondo23,
    "fondo24" to R.drawable.fondo24,
    "fondo25" to R.drawable.fondo25,
    "fondo26" to R.drawable.fondo26,
    "fondo27" to R.drawable.fondo27,
    "fondo28" to R.drawable.fondo28,
    "fondo29" to R.drawable.fondo29,
)